### PR TITLE
ci: simplify nasm installation

### PR DESCRIPTION
**Pull request by rr-**

### CODE REVIEW

**Comment by rr-** [comment]
Also we have another problem:

>Error: Unable to process command '::add-path::C:\Program Files (x86)\Microsoft Visual Studio\Installer' successfully.

Unfortunately I'm not sure how to fix this one…

**Comment by Luni-4** [comment]
Since we are on Windows we need this: `echo "$VsPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append`

The same goes for the other line

**Comment by rr-** [comment]
Fixed

**Review by Luni-4 — APPROVED** [review]
Thanks! :)

**Pull request merged**
