### PR TITLE
Mingw

### PR DESCRIPTION
**Pull request by abakum**
pypiwin32 now not compatible with MINGW
`pacman -S ${MINGW_PACKAGE_PREFIX}-ffms2` place libffms2-?.dll to /bin

### CODE REVIEW

**Comment by abakum** [comment]
image

**Comment by Luni-4** [comment]
Hello @abakum! Thanks for your PR! :)

I fixed the Windows CI, please rebase your PR to see the changes. Could you also squash the commits in a single one?

**Comment by abakum** [comment]
I will try, but for this I need to learn git. Now I did it through the github web interface.
I have a problem with the test.py in windows and MINGW:
image

**Comment by Luni-4** [comment]
So can we close this PR in favor of #21?

**Pull request closed without merging**
