### PR TITLE
Release source code on Linux

### PR DESCRIPTION
**Pull request by Luni-4**
Please remove the last commit on the `master` branch before merging this PR

### CODE REVIEW

**Comment by rr-** [comment]
Releases are a one way trip, there's no "removing the commits" after burning a number as proved by recent experiences over the e-mail.

**Comment by Luni-4** [comment]
> Releases are a one way trip, there's no "removing the commits" after burning a number as proved by recent experiences over the e-mail.

Wrong approach. `0.4.5` and `0.4.5.1` don't exist on `PyPI` and the `Github Release` contains identical  `ffms2.zip` file, so they're redundant. Pretty wrong really.

**Comment by rr-** [comment]
Just because a package does not exist on pypi it doesn't mean we didn't burn a version number and a tag on master. I'm not a fan of force pushes in the production code.

Also me being too busy to manage these packages in a committed way doesn't mean that I am going to accept this kind of attitude.

**Comment by Luni-4** [comment]
> Just because a package does not exist on pypi it doesn't mean we didn't burn a version number and a tag on master. I'm not a fan of force pushes in the production code.
> 
> Also me being too busy to manage these packages in a committed way doesn't mean that I am going to accept this kind of attitude.

The best way would be having a tag that represents both `PyPI` and `GitHub Releases`. Much simpler for users because they would know that tag matches all of the distribution platforms also. Having not representative tags generate confusion.

**Pull request merged**
