### PR TITLE
Fix search ffms2.dll and call FFMS_Init for MINGW

### PR DESCRIPTION
**Pull request by abakum**
`pacman -S ${MINGW_PACKAGE_PREFIX}-ffms2` place libffms2-?.dll to /bin
not to /windows with name ffms2.dll

For MINGW pywin32 not found in repos: `pacman -Ss python-pywin32`
(look: msys2/MINGW-packages#751)
and cannot be installed with `pip install pypiwin32`
Therefore, it is not possible to use pythoncom
(look: https://github.com/bubblesub/pyffms2/pull/21)

### CODE REVIEW

**Comment by Luni-4** [comment]
@abakum 

Thanks again for your PR, but you don't need to open a new PR every time you change something, just modify your commit message (as I've explained [here](https://github.com/bubblesub/pyffms2/pull/21#issuecomment-638742570)) locally and the push to you fork. The PR will be updated automatically :)

If you don't know what should be written inside, look at the other commit messages of this repository.

**Comment by Luni-4** [comment]
@abakum 

If you want I can merge your PR and change the title accordingly :)

**Comment by rr-** [comment]
We can't quite merge it – the comments from the earlier instance of this pr are still unaddressed

**Comment by abakum** [comment]
Hi @Luni-4 I'm not against
Hi @rr If comments in the code do not help please remove them. I speak english via Google \8^)

**Comment by abakum** [comment]
image

**Comment by abakum** [comment]
image

**Comment by abakum** [comment]
image

**Comment by rr-** [comment]
@Luni-4 what do you think? Is it sufficient? In any case I'd like to reformat the code with Black.

**Comment by Luni-4** [comment]
@rr- 

If @abakum agrees, we could merge his PR and later:
- Change the commit title
- Format the code
- Improve the comments

**Comment by rr-** [comment]
OK, I'll take care of this :+1:

**Comment by rr-** [comment]
@Luni-4 can you please confirm that this won't break Windows builds? I see that my Linux version is `'3.6.9 (default, Apr 18 2020, 01:56:04) \n[GCC 8.4.0]'`

**Comment by Luni-4** [comment]
@rr- 

If the CI is good, it shouldn't break Windows

**Comment by abakum** [comment]
instead
```
def ffms_init():
        if "[GCC" in sys.version:
            import atexit
            import pythoncom
```
use
```
def ffms_init():
        if not "[GCC" in sys.version:
            import atexit
            import pythoncom
```

**Comment by rr-** [comment]
Merged with fixes to master, in case it isn't working, please open a new issue :+1:

**Pull request closed without merging**
